### ISSUE TITLE
maybe no need to use files to pass around data

### ISSUE THREAD

**Issue by mimoo** [mimoo/mirai-bot#59]
```
      - name: read dep-auditors list
        id: dep-auditors
        run: |
          output=$(cat ./.github/dep-auditors.json | jq -r 'join(",")')
          echo "::set-output name=list::${output}"
      - name: require dep-audit review if TCB deps changed
        if: ${{ steps.verify-lsr.outputs.diff || steps.verify-lec.outputs.diff }}
        uses: libra/actions/require-review@a9c5709
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          users: ${{ steps.dep-auditors.outputs.list }}
```

`set-output` can be used
